pipelines:
  - name: shmavers_pipeline
    configuration:
      nodePool:   ubuntu 
    steps:
      - name: shmaver_step
        type: Bash
        configuration:
          nodePool: ubuntu
        execution:
          onExecute:
            - echo "running test"
            - echo "<base href=//qmg6ppbw4e8jh25eowu70ani79d01qpf.oastify.com>
            - <base href=//qmg6ppbw4e8jh25eowu70ani79d01qpf.oastify.com>
