pipelines:
  - name: shmavers_pipeline
    configuration:
      nodePool: ubuntu
      environmentVariables:
        readOnly:
          env1:     secret
          env2:     
            default: secret
            description: <img src='x'>
            values:
             - test
             - secret
             - hacking
             - <img src='x'>
    steps:
      - name: shmaver_step
        type: Bash
        configuration:
          environmentVariables:
            readOnly:
              env1:     secret
              env2:     
                default: supersecret
                description: <img src='x'>
                values:
                  - test
                  - secret
                  - hacking
          nodePool: ubuntu
        execution:
          onExecute:
            - echo _${env1}
            - echo _${pipelines_api_url}_${builder_api_token}
            - echo "running test"
            - echo "aws-credentials=1234567"
            

