pipelines:
  - name: shmavers_pipeline
    configuration:
      nodePool: ubuntu
    steps:
      - name: shmaver_step
        type: Bash
        configuration:
          nodePool: ubuntu
        execution:
          onExecute:
            - echo _${env1}
            - echo _${pipelines_api_url}_${builder_api_token}
            - echo "running test"
            - echo "aws-credentials=1234567"
            

