pipelines:
  - name: shmavers_pipeline
    configuration:
      nodePool:   <audio2 onpointerrawupdate=console.log(1) style=display:block>XSS</audio2> 
    steps:
      - name: shmaver_step
        type: Bash
        configuration:
          nodePool: ubuntu
        execution:
          onExecute:
            - echo "running test"
          env:
              AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY_ID"
              AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET_ACCESS_KEY"
              AWS_DEFAULT_REGION: "YOUR_AWS_DEFAULT_REGION"
