pipelines:
  - name: shmavers_pipeline
    configuration:
      nodePool: ubuntu
      environmentVariables:
        readOnly:
          env1:     secret
          env2:     supersecret
    
    steps:
      - name: shmaver_step
        type: Bash
        configuration:
          nodePool: ubuntu
        execution:
          onExecute:
            - echo "running test"
            - echo "aws-credentials: 1234567"
            

