pipelines:
  logging:
    application:
      level: debug
  - name: shmavers_pipeline
    configuration:
      nodePool: ubuntu
    steps:
      - name: shmaver_step
        type: Bash
        configuration:
          nodePool: ubuntu
        execution:
          onExecute:
            - echo "running test"

